### ISSUE TITLE
Unable to load template 'file:header.tpl' in 'store/index.tpl'

### ISSUE THREAD

**Issue by jacobjake1** [partydragen/Nameless-Store#16]
Uncaught SmartyException
Unable to load template 'file:header.tpl' in 'store/index.tpl'
(File: /home/plexicne/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php)

**Comment by partydragen** [comment]
Hi

This is caused by your custom template, I believe you have uploaded the DefaultRevamp files into your own custom template but the custom template don't support that

Your custom template most likey included their own store files with you overrided that you need to change back to, if not then the custom template don't support the module

Contact your template author

**Comment by jacobjake1** [comment]
Im using Lithium - I kinda figured it would work with that, do you know?

**Comment by jacobjake1** [comment]
It doesn't even work on the DefaultRevamp either for me, same error

**Comment by partydragen** [comment]
> Im using Lithium - I kinda figured it would work with that, do you know?

Lithium is already supporting the module, you have overrided their files, redownload Lithium and reupload their own files

**Comment by partydragen** [comment]
> It doesn't even work on the DefaultRevamp either for me, same error

Not possible, that error is because its on Lithium with using a different file layouts

**Comment by jacobjake1** [comment]
> > Im using Lithium - I kinda figured it would work with that, do you know?
> 
> Lithium is already supporting the module, you have overrided their files, redownload Lithium and reupload their own files

I just fresh installed Lithium, all I did was drag and drop the store folder from DefaultRevamp into the Lithium folder. Same error

**Comment by partydragen** [comment]
> > > Im using Lithium - I kinda figured it would work with that, do you know?
> > 
> > 
> > Lithium is already supporting the module, you have overrided their files, redownload Lithium and reupload their own files
> 
> I just fresh installed Lithium, all I did was drag and drop the store folder from DefaultRevamp into the Lithium folder. Same error

As im telling "drop the store folder from DefaultRevamp into the Lithium folder" is wrong thats is exactly the issue, you will need to use Lithium files Only

**Comment by jacobjake1** [comment]
> 

I guess I am misunderstanding, how can I use Lithium files only, but also use the store module? You say "redownload Lithium and reupload their own files" what would that be exactly?

**Comment by partydragen** [comment]
> > 
> 
> I guess I am misunderstanding, how can I use Lithium files only, but also use the store module? You say "redownload Lithium and reupload their own files" what would that be exactly?

Just do the same way to installed Lithium, Reupload the Lithium template and DON'T copy the DefaultRevamp files into Lithium

**Comment by jacobjake1** [comment]
> > > 
> > 
> > 
> > I guess I am misunderstanding, how can I use Lithium files only, but also use the store module? You say "redownload Lithium and reupload their own files" what would that be exactly?
> 
> Just do the same way to installed Lithium, Reupload the Lithium template and DON'T copy the DefaultRevamp files into Lithium

That's what I thought it was at first, but im still getting the same exact error

**Comment by partydragen** [comment]
> > > > 
> > > 
> > > 
> > > I guess I am misunderstanding, how can I use Lithium files only, but also use the store module? You say "redownload Lithium and reupload their own files" what would that be exactly?
> > 
> > 
> > Just do the same way to installed Lithium, Reupload the Lithium template and DON'T copy the DefaultRevamp files into Lithium
> 
> That's what I thought it was at first, but im still getting the same exact error

Then you're uploading it wrong, When you download Lithium then you go into the zip and drag the Lithium template into your website files im not sure how Lithium template work either you drag it into your root installation or into /custom/templates/

Go ask Lithium support instead if you don't remember how to upload their template

**Comment by jacobjake1** [comment]
There's nothing inside Lithium, fresh install. 

Yes it's inside of /custom/templates/

 I've only uploaded to the panel_templates, and modules.

I found out that it works on another module called Nexus though? So...

**Comment by partydragen** [comment]
Lithium have their own store folder /custom/templates/Lithium/store when you downloaded Lithium template, you need to drag that folder into /custom/templates/Lithium/

**Comment by jacobjake1** [comment]
I got the Lithium store folder uploaded, same error :/

**Comment by partydragen** [comment]
> I got the Lithium store folder uploaded, same error :/

Im not able to help anymore i don't know what you're doing wrong, This have worked for everyone else who has done this mistake

**Comment by jacobjake1** [comment]
Then how does it not even work on the DefaultRevamp, doesn't make sense

**Comment by partydragen** [comment]
It do work on DefaultRevamp, if it don't then you have not uploaded the files there once again incorrectly uploading files

When you installed the module you drag the 2 folders inside the upload folder into your root installation /

**Comment by jacobjake1** [comment]
If I have been incorrectly installing this the entire time, then how does it work on a different templates with no changes?

**Comment by partydragen** [comment]
> If I have been incorrectly installing this the entire time, then how does it work on a different templates with no changes?

Templates like Nexus already provide support for the Store Module, same as Lithium
So you don't need to add any files into them as they already have the files added for the Store Module
But in your case you have overrided Lithium own store files for the Store Module with DefaultRevamp with cause this error
As for DefaultRevamp you have not uploaded the files into there, As DefaultRevamp don't include the files by default

**Comment by jacobjake1** [comment]
How can I have overrided Lithium own store files if im on a fresh install?

**Comment by partydragen** [comment]
> I just fresh installed Lithium, all I did was drag and drop the store folder from DefaultRevamp into the Lithium folder. Same error

You told it there ^^ With is incorrect as Lithiumprovide their own store folder with is made for the Lithium template, and the error you're telling is telling the Store folder you're using on Lithium belongs to DefaultRevamp

**Comment by jacobjake1** [comment]
I've tried without uploading the DefaultRevamp to the Lithium folder, like it's a fresh install, there's nothing uploaded into it besides itself. It has the default store folder yes, same error.

**Comment by jacobjake1** [comment]
> There's nothing inside Lithium, fresh install.
> 
> Yes it's inside of /custom/templates/
> 
> I've only uploaded to the panel_templates, and modules.
> 
> I found out that it works on another module called Nexus though? So...

Like what this says

**Comment by jacobjake1** [comment]
I got it to work - but I am now getting this error when I try to checkout

Uncaught Error
Call to a member function isPlayerSystemEnabled() on null
(File: /home/plexicne/public_html/modules/Store/classes/Product.php)
